# Generated by Django 6.0.3 on 2026-04-03 01:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TimeCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_name', models.CharField(max_length=120)),
                ('week_ending', models.DateField()),
                ('project_name_location', models.CharField(blank=True, max_length=180)),
                ('prepared_by', models.CharField(max_length=120)),
                ('prepared_date', models.DateField()),
                ('approved_by', models.CharField(blank=True, max_length=120)),
                ('approved_date', models.DateField(blank=True, null=True)),
                ('entered_by', models.CharField(blank=True, max_length=120)),
                ('entered_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('certified', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('approver_comment', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TimeCardLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_order', models.PositiveIntegerField(default=1)),
                ('job_number', models.CharField(blank=True, max_length=30)),
                ('phase', models.CharField(blank=True, max_length=30)),
                ('category', models.CharField(blank=True, max_length=60)),
                ('description', models.CharField(blank=True, max_length=120)),
                ('mon_st', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('mon_ot', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('tue_st', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('tue_ot', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('wed_st', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('wed_ot', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('thu_st', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('thu_ot', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('fri_st', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('fri_ot', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('sat_st', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('sat_ot', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('sun_st', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('sun_ot', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('vacation', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('holiday', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('comp_time', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('funeral_bereavement', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('jury_duty', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('timecard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='timecard.timecard')),
            ],
            options={
                'ordering': ['line_order', 'id'],
            },
        ),
    ]
